service: injoy-click

plugins:
  - serverless-offline

provider:
  name: aws
  runtime: nodejs12.x

functions:
  getMemes:
    handler: src/endpoints/getMemes/getMemes.handler
    events:
     - http:
         path: memes
         method: get
         cors: true
         
  getNews:
    handler: src/endpoints/getNews/getNews.handler
    events:
     - http:
        path: news
        method: get
        cors: true

  getTweets:
    handler: src/endpoints/getTweets/getTweets.handler
    events:
     - http:
         path: tweets
         method: get
         cors: true
